[package]
name = "firestore-db-and-auth"
version = "0.1.0"
authors = ["David Gräff <david.graeff@web.de>"]
edition = "2018"
license = "MIT"
description = "This crate allows easy access to your Google Firestore DB via service account or OAuth impersonated Google Firebase Auth credentials."

[dependencies]
url  = "1.7.2"
reqwest = "^0.9"
serde_derive = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
chrono = { version = "0.4", features = ["serde"] }
biscuit = "0.2" # jwt, jws, jwk support
ring = "0.14" # crypto; signing for jws
untrusted = "0.6.2" # used by ring
regex = "1.1" # for extracting a pem private key
rustc-serialize = "0.3" # for base64 pem -> psck#8
bincode = { version = "1.1", optional = true }

[dependencies.rocket]
version = "^0.4.1"
default-features = false
optional = true

[dependencies.rocket_contrib]
version = "^0.4.1"
default-features = false
features = ["json","redis_pool"]
optional = true

[features]
default = ["faststart"]
rocket_support = ["rocket","rocket_contrib"]
faststart = ["bincode"]