[package]
name = "firestore-db-and-auth"
version = "0.3.1"
authors = ["David Gräff <david.graeff@web.de>"]
edition = "2018"
license = "MIT"
description = "This crate allows easy access to your Google Firestore DB via service account or OAuth impersonated Google Firebase Auth credentials."
readme = "readme.md"
keywords = ["firestore", "auth"]
categories = ["api-bindings","authentication"]
maintenance = { status = "passively-maintained" }
repository = "https://github.com/davidgraeff/firestore-db-and-auth-rs"

[dependencies]
url  = "^2.1"
reqwest = { version ="^0.9", default-features = false }
serde_derive = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
chrono = { version = "^0.4", features = ["serde"] }
biscuit = "^0.3"
ring = "^0.16"
untrusted = "^0.7"
regex = "^1.2"
rustc-serialize = "^0.3"

[dependencies.rocket]
version = "^0.4"
default-features = false
optional = true

# Render the readme file on doc.rs
[package.metadata.docs.rs]
features = [ "external_doc", "rocket_support" ]

[features]
default = ["default-tls"]
rocket_support = ["rocket"]
rustls-tls = ["reqwest/rustls-tls"]
default-tls = ["reqwest/default-tls"]
external_doc = []
