[package]
name = "firestore-db-and-auth"
version = "0.2.1"
authors = ["David Gräff <david.graeff@web.de>"]
edition = "2018"
license = "MIT"
description = "This crate allows easy access to your Google Firestore DB via service account or OAuth impersonated Google Firebase Auth credentials."
readme = "readme.md"
keywords = ["firestore", "auth"]
categories = ["api-bindings","authentication"]
maintenance = { status = "passively-maintained" }

[dependencies]
url  = "^2.1"
reqwest = "^0.9"
serde_derive = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
chrono = { version = "^0.4", features = ["serde"] }
biscuit = "^0.3"
ring = "^0.16"
untrusted = "^0.7"
regex = "^1.2"
rustc-serialize = "^0.3"

[dependencies.rocket]
version = "^0.4"
default-features = false
optional = true

[dependencies.rocket_contrib]
version = "^0.4"
default-features = false
features = ["json","redis_pool"]
optional = true

[features]
default = []
rocket_support = ["rocket","rocket_contrib"]
