name: StaticLibMusl

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: juankaram/rust-musl-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Check for leftover println
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: ./ci.sh
    - name: Build and Test
      run: cargo test --features rustls-tls --no-default-features --target x86_64-unknown-linux-musl
