name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: echo $SERVICE_ACCOUNT_JSON > firebase-service-account.json && cargo build --verbose
    - name: Run tests
      run: echo $SERVICE_ACCOUNT_JSON > firebase-service-account.json && cargo test --verbose
